inetaf/netaddr

go.mod, netaddr.go
Make module mode happy and enforce the correct import path, per email.
```
11:43 $ go build                    
go: cannot find main module, but found .git/config in /home/matt/src/inet.af/netaddr
to create a module there, run:
go mod init
```
=> netaddr: initial go.mod, enforce import path

netaddr.go, netaddr_test.go
Thoughts welcome on the "what to do with nil" TODO. I am tempted to panic to avoid an error return and also a potential nil pointer dereference in calling code. But I'm open to all suggestions.
Fixes #2.
=> netaddr: implement IP.IPAddr for interop with existing code

netaddr.go
A nice simplification as suggested by @bradfitz in #3.
=> netaddr: simplify IPv4 IPAddr conversion

netaddr_test.go
I had a brief discussion with @danderson about the ipv4i representation and was curious if clever tricks could be used to speed up IPv6 in the same fashion. Perhaps the use of the IPv6-mapped IPv4 representation or using some currently unallocated IPv6 bits for flags could be promising.
For now, here's some basic benchmarks for IPv6 as well. There's no easy constructor for IPv6 at the moment so I'm not sure this is a fair comparison.
```
✔ ~/src/inet.af/netaddr [mdl-bench-ipv6 L|✔] 
13:02 $ go test -bench=.
goos: linux
goarch: amd64
pkg: inet.af/netaddr
BenchmarkStdIPv4-24              9895953               114 ns/op              16 B/op          1 allocs/op
BenchmarkIPv4-24                12732474                89.4 ns/op             4 …
```
=> netaddr: benchmarks for IPv6

netaddr.go, netaddr_test.go
Make the linter happy. The file-ignore directive isn't ideal but it's probably okay for tests.
=> netaddr: fix staticcheck issues identified in #14

netaddr.go, netaddr_test.go
With this and #16, all of my CoreRAD needs have been met by netaddr. I also slightly adjusted the unicast fixtures to be more correct and not overlap with link-local.
=> netaddr: add IP.IsLinkLocalUnicast method

.github/workflows/linux.yml
Use a build matrix to test with Go 1.11, 1.12, 1.13 and Go 1.14.
=> ci: use build matrix to test with multiple Go versions

.github/workflows/linux.yml
Use the correct property matrix.go-version to fix the Github action and
use the Go version defined in the build matrix.
=> ci: fix matrix property name after #22

netaddr.go, netaddr_test.go
These are the only two "constants" I need at the moment. The standard library exposes a few more.
It'd be nice if these could be immutable but I think this is probably reasonable.
=> netaddr: add initial well-known IP addresses

netaddr.go, netaddr_test.go
=> netaddr: fix #29, prevent integer underflow in IPPrefix.Contains

netaddr_test.go
A trivial change, but it's good to verify the address family logic checks anyway.
=> netaddr: full test coverage for IPPrefix.Contains

netaddr_test.go
=> netaddr: test coverage for FromStdIPRaw with 4-byte IPv4 and bad net.IP

netaddr.go
I assume that `maxUint16` was added to avoid a `math` import, but then `math.MaxUint8` was also used for prefix contains logic. I don't know enough about the current state of the linker to know if this is truly necessary, but doing this allows us to completely remove the math import.
If the linker is smart enough to discard the rest of the math code, I'd vote for getting rid of both of these and importing math anyway for clarity.
=> netaddr: add maxUint8, remove math import

go.mod, netaddr.go, netaddr_test.go
ParseIP isn't documented to do dns resolution, it really shouldn't
anyway. A resolving function should be named something else, maybe even
ResolveIPAddr to match stdlib.
I originally was falling back to a combination of ParseIP for the ip and
ResolveIPAddr for the zone info, but according to RFC4007 splitting on
'%' is enough.
Signed-off-by: Manuel Mendez <mmendez534@gmail.com>
Fixes #32
=> Avoid net.ResolveIPAddr in ParseIP

netaddr_test.go
=> netaddr: add benchmarks for IP.Prefix masking, gofmt

netaddr.go, netaddr_test.go
name                              old time/op    new time/op    delta
IPPrefixMasking/IPv4_/32-8          32.6ns ± 3%    29.2ns ± 3%  -10.47%  (p=0.000 n=17+20)
IPPrefixMasking/IPv4_/17-8          34.6ns ± 3%    32.8ns ± 4%   -5.23%  (p=0.000 n=20+19)
IPPrefixMasking/IPv6_/128-8         52.5ns ± 4%    43.0ns ± 2%  -18.10%  (p=0.000 n=20+19)
IPPrefixMasking/IPv6_/65-8          59.7ns ± 3%    47.4ns ± 2%  -20.66%  (p=0.000 n=20+19)
IPPrefixMasking/IPv6_zone_/128-8     103ns ± 4%      82ns ± 3%  -20.29%  (p=0.000 n=20+20)
IPPrefixMasking/IPv6_zone_/65-8      109ns ± 5%      93ns ± 3%  -14.08%  (p=0.000 n=20+20)
=> IP.Prefix: speed up by removing type switch and using fewer ops for masking.

netaddr.go, netaddr_test.go
Another reasonable behavior is to return `p.IP.ipImpl == nil`, considering a zero-value IP to be included in a zero-value Prefix.
=> Don't panic on zero-value IP in Contains

netaddr.go, netaddr_test.go
As suggested by @bradfitz in https://github.com/inetaf/netaddr/pull/46#issuecomment-671100081.
=> introduce IPPrefix.Masked for zeroing masked address bits

go.mod, go.sum, netaddr.go, netaddr_test.go
The new representation is basically:
```go
type IP struct {
addr [16]byte
zone *zone // always the same pointer for a given zone string
}
```
See '"The zone pointer" alternative' comment from
https://github.com/inetaf/netaddr/issues/53#issuecomment-747849869
Fixes #53
=> Change representation to 20 bytes (32-bit) or 24 bytes (64-bit)

netaddr_test.go
This passes on master but fails in #63 (at the moment).
This makes it interesting enough to keep.
=> add ParseIP test case

netaddr_test.go
Thanks for creating this library! This is something that I had wished existed before, so I'm glad you've taken the initiative to create this. I want to contribute to this effort and thought that adding some test cases would be a good way to go about it. If you have hints for other "good first issues" to tackle, I'd appreciate the direction!
As long as the Prior or Next address is valid, then doing the
inverse operation should get us the IP we started with.
This also adds a few test cases for localhost addresses.
=> Test that Prior.Next and Next.Prior return same IP

netaddr.go
Several Tailscale packages each have their own copy of these helpers.
=> netaddr: add MustParse* helpers

netaddr.go, netaddr_test.go
This allows IP manipulation operations to operate on IPs as two registers, which empirically
leads to significant speedups, in particular on OOO superscalars where the two halves can
be processed in parallel.
```
name                              old time/op    new time/op    delta
StdIPv4-8                            146ns ± 2%     141ns ± 2%    -3.42%  (p=0.016 n=5+5)
IPv4-8                               120ns ± 1%     107ns ± 2%   -10.65%  (p=0.008 n=5+5)
IPv4_inline-8                        120ns ± 0%     118ns ± 1%    -1.67%  (p=0.016 n=4+5)
StdIPv6-8                            211ns ± 2%     215ns ± 1%    +2.18%  (p=0.008 n=5+5)
IPv6-8                               281ns ± 1%     252ns ± 1%   -10.19%  (p=0.008 n=5+5)
IPv4Contains-8                      11.8ns ± 4%     4.7ns ± 2% …
```
=> Change the representation of IP to a pair of uint64s.

netaddr.go, netaddr_test.go, slow_test.go
The goal of this implementation is to be slow, but very readable, and a point of comparison for optimized implementations: faster implementations should behave exactly like parseIPSlow on the set of valid and invalid inputs, and the tests now enforce that in addition to parity with net.ParseIP.
Mostly this is useful if we implement behavior that diverges from net.ParseIP. By having a reference parser in netaddr itself, we can evolve the optimized/not-as-readable implementation in tandem with our own reference impl.
=> Add a slow, but correct ParseIP as a reference implementation.

netaddr.go, netaddr_test.go
```
name            old time/op    new time/op    delta
ParseIPv4-8       63.2ns ± 4%    20.1ns ± 4%  -68.17%  (p=0.000 n=19+19)
StdParseIPv4-8    93.9ns ± 3%    93.3ns ± 3%     ~     (p=0.211 n=20+19)
```
=> Speed up parseIPv4 3.3x.

netaddr.go, netaddr_test.go
The mask needs to be applied on both sides.
Regression introduced in 4eb479db13f8b816537f38c664776b193c7a86ec
and caught far away in Tailscale's tests.
Signed-off-by: Josh Bleecher Snyder <josharian@gmail.com>
=> fix IPPrefix.Contains

.gitignore, .gitmodules, README.md, fuzz.go, go.mod, go.sum
I decided in this case to also commit the corpus, because it has been built up over several different implementations of netaddr, which means it has coverage hints that might be hard to discover given only one of those implementations.
=> add a fuzz function and corpus

netaddr.go, netaddr_test.go, slow_test.go
With this change, netaddr is no longer dependent on net.ParseIP for its
ParseIP implementation. It's also 2-4x faster than net.ParseIP and
allocation-free, except for v6+zone addresses which are still slower and
require 1 allocation.
```    
name                      old time/op    new time/op    delta
ParseIP/v4-8                22.0ns ± 2%    24.5ns ± 1%   +11.46%  (p=0.016 n=5+4)
ParseIP/v6-8                 169ns ± 2%      91ns ± 2%   -45.97%  (p=0.008 n=5+5)
ParseIP/v6_ellipsis-8        140ns ± 2%      68ns ± 5%   -51.32%  (p=0.008 n=5+5)
ParseIP/v6_v4-8              216ns ± 1%      71ns ± 1%   -67.19%  (p=0.008 n=5+5)
ParseIP/v6_zone-8            526ns ± 1%     222ns ± 1%   -57.89%  (p=0.008 n=5+5)
StdParseIP/v4-8             94.5ns ± 2%    89.0ns ± 1%    -5.78%  (p=0.008 n=5+5) …
```
=> Parse IPv6 without net.ParseIP, and make it faster.

inlining_test.go, netaddr.go, netaddr_test.go
Allocation-free way to test whether an IPRange is an IPPrefix and get it.
(Needs tests before submitting but I gotta get off the computer now.)
Needed this for some Tailscale stuff.
=> add IPRange.Prefix

netaddr.go, netaddr_test.go
Makes long strings parse a little faster, because unlike net.SplitHostPort, we
can entirely ignore the contents of the ip and port portions, and let our subsequent
parser deal with errors there.
```
ParseIPPort/v4-8             56.5ns ± 3%    57.4ns ± 3%     ~     (p=0.421 n=5+5)
ParseIPPort/v6-8              143ns ± 2%     117ns ± 4%  -18.44%  (p=0.008 n=5+5)
ParseIPPort/v6_ellipsis-8     112ns ± 5%     100ns ± 1%  -10.68%  (p=0.008 n=5+5)
ParseIPPort/v6_v4-8           143ns ± 5%     139ns ± 1%     ~     (p=0.175 n=5+5)
ParseIPPort/v6_zone-8         272ns ± 1%     256ns ± 1%   -5.96%  (p=0.008 n=5+5)
```
=> Remove dependency on stdlib for ParseIPPort, make faster.

netaddr.go, netaddr_test.go
Hi,
Thanks for this library, i enjoy using it as a more convenient api compared to the stdlib variant.
I have a use case where i need to extract a prefix with given bit length from a existing larger prefix/set.
If you find this addition useful, please consider it.
=> Add extractPrefix to IPPrefix and IPSet

inlining_test.go, netaddr.go, netaddr_test.go
The guts of this change are:
// uint128 represents a uint128 using two uint64s.
// Index 0 contains the high bits, index 1 contains the low.
type uint128 [2]uint64
Then it replaces IP.hi and IP.lo with IP.addr of type uint128. Same
shape in memory, but with a name and type and lets us pass around both
parts together in one variable (as now used by IPRange.Prefix and
IPRange.Prefixes), including putting methods on them (moved from
the now-deleted ip16 type)
No change in inlining.
=> Remove ip16 type, change it into uint128 type, use it in IP also

inlining_test.go, netaddr.go, netaddr_test.go
More to go, but this is a start...
```
name             old time/op    new time/op    delta
IPRangePrefix-4     822ns ± 7%     149ns ± 5%  -81.87%  (p=0.008 n=5+5)
name             old alloc/op   new alloc/op   delta
IPRangePrefix-4     0.00B          0.00B          ~     (all equal)
name             old allocs/op  new allocs/op  delta
IPRangePrefix-4      0.00           0.00          ~     (all equal)
```
Before:
```
flat  flat%   sum%        cum   cum%
2.49s 57.11% 57.11%      2.49s 57.11%  inet.af/netaddr.uint128.bitSet
1.30s 29.82% 86.93%      3.79s 86.93%  inet.af/netaddr.comparePrefixes
0.15s  3.44% 90.37%      0.15s  3.44%  inet.af/netaddr.IP.IsZero (inline)
0.10s  2.29% 92.66%      0.10s  2.29%  inet.af/netaddr.IPRange.prefixMaker.func1
0.06s  1.38% 94.04%      0.07s  1.61% …
```
=> optimize IPRange.Prefix[es], common prefix length, etc

netaddr.go, netaddr_test.go
Also probably faster implementation (by accident).
Updates #84 (more remains)
Signed-off-by: Brad Fitzpatrick <brad@danga.com>
=> make IPRange.Valid report false when zones differ

inlining_test.go, netaddr.go
Makes String faster, and only makes 1 heap allocation for most IP shapes.
(v6+zone where the IP is the longest it can be can still cause extra allocs
to append the zone string)
IP.String is faster than net.IP.String for all cases, except IPv4-mapped IPv6,
because the stdlib prints it as an IPv4 and we print it as an IPv6, and so
need to do more work to format it.
```
name                    old time/op    new time/op    delta
IPString/v4-8              267ns ± 1%      53ns ± 3%  -80.03%  (p=0.000 n=9+10)
IPString/v6-8              268ns ± 1%     130ns ± 3%  -51.62%  (p=0.000 n=9+10)
IPString/v6_ellipsis-8     198ns ± 3%     117ns ± 3%  -40.74%  (p=0.000 n=10+10)
IPString/v6_v4-8           306ns ± 3%     121ns ± 2%  -60.32%  (p=0.000 n=9+10)
IPString/v6_zone-8         302ns ± 3%     135ns …
```
=> Implement IP.String without relying on the stdlib.

netaddr.go, netaddr_test.go
Updates #101
(We need to review the rest of the IPPrefix methods before we can close it.)
Signed-off-by: Josh Bleecher Snyder <josharian@gmail.com>
=> make IPPrefix.Contains return false for invalid receivers

netaddr.go, netaddr_test.go
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkParseIP/v4-8                  22.9          18.4          -19.65%
BenchmarkParseIP/v6-8                  77.4          77.9          +0.65%
BenchmarkParseIP/v6_ellipsis-8         56.5          55.5          -1.77%
BenchmarkParseIP/v6_v4-8               63.8          58.1          -8.93%
BenchmarkParseIP/v6_zone-8             144           140           -2.78%
BenchmarkParseIPPort/v4-8              42.5          37.8          -11.06%
BenchmarkParseIPPort/v6-8              99.6          100           +0.40%
BenchmarkParseIPPort/v6_ellipsis-8     80.2          79.2          -1.25%
BenchmarkParseIPPort/v6_v4-8           86.9          81.8          -5.87%
BenchmarkParseIPPort/v6_zone-8         176 …
```
=> Optimizes parseIPv4

inlining_test.go, netaddr.go, netaddr_test.go
Adjust some tests to check behavior on invalid prefixes.
=> Use IPPrefix.Valid in other IPPrefix methods.

go.mod, go.sum, netaddr.go
Removes the remaining allocation from IPv6 IP parsing.
=> use intern.GetByString in IP.WithZone

netaddr_test.go
With this change, test coverage for ParseIP is now 100%!
=> netaddr: more test cases for ParseIP

uint128.go
=> netaddr: change uint128.commonPrefixLen receiver name for consistency

ipset.go, ipset_test.go
Fixes #123.
I set the merge-base to #124 so it shows only the new functionality.
=> Implement IPSet.Invert and IPSet.Intersect.

ipset.go, ipset_test.go
This depends on the bug fixes in https://github.com/inetaf/netaddr/pull/124 for its tests to pass.
=> add IPSet.Equal

README.md
Replace with a more accurate assessment of the package's maturity level.
=> readme: remove scary warning

netaddr.go
=> netaddr: fix doc comment typo for IPPrefix.String

.github/workflows/linux.yml, .github/workflows/staticcheck.yml
Since renaming the branch to `main`, the GitHub actions didn't seem to
have run on pushes to that branch. Fix it by adjusting the branch name
in the workflows `on.push.branches`.
=> .github: run GitHub actions on main branch pushes

netaddr.go, netaddr_test.go
This ensures ParseIP errors always begin with `ParseIP(<input>): ` when
converted to strings.
=> netaddr: return parseIPError for all ParseIP errors

.github/workflows/linux.yml
Drop 1.14 and keep 1.12, 1.15.
=> .github: add Go 1.16 to matrix

inlining_test.go, netaddr.go, netaddr_test.go
Corresponding to the respective standard library `net.IP` methods: [`net.IP.IsInterfaceLocalMulticast`](https://golang.org/pkg/net/#IP.IsInterfaceLocalMulticast) and [`net.IP.IsLinkLocalMulticast`](https://golang.org/pkg/net/#IP.IsLinkLocalMulticast).
=> Add IP.{Interface,Link}LocalMulticast methods

README.md
Rename "Maturity" section to "Status", move it to the top,
and indicate that we take quality and dependencies seriously.
Also, remove the TODO from the README.
=> README: document stance on quality and dependencies

netaddr.go
This doesn't alter the behavior of dependent code, but does
make the sort order slightly more "natural" and consistent.
Fixes #145.
=> Make IPRange.less sort subset ranges after their superset.

fuzz.go
Two commits. The first is safe to merge any time.
The second one is not: It'll cause a bunch of fuzz failures.
We need to fix #169 first.
The new fuzzing power is pulling its weight:
It found a few other new, unrelated bugs,
which I have sent fixes for.
=> fuzz more invalid values

netaddr.go
These helped me to cross reference inet.af/netaddr, net.IP, and
github.com/mellowdrifter/bogons for #151.
Signed-off-by: Alex Willmer <alex@moreati.org.uk>
=> Add RFC references for IP.Is<Property>() methods

netaddr.go, netaddr_test.go
Fixes #51. There's a bit of duplication between `IP.string6` and `IP.StringExpanded` but I was able to remove some logic regarding adding `::` compression so it seemed worth duplicating.
=> netaddr: add IP.StringExpanded to expand IPv6 address strings

example_test.go, netaddr.go, netaddr_test.go
Another helper I need for CoreRAD. I'd also like to add functions for IPv6 ULA detection, so maybe we can mirror Go 1.17's https://tip.golang.org/pkg/net/#IP.IsPrivate in a follow-up PR.
Notably the new function matches the stdlib logic but since we don't have IPv4zero (pending #187) or IPv4 broadcast, we just declare those inline. It's probably not a big deal though.
I know this has grown organically, but as a matter of tidying, I arrange some table test fields alphabetically and adjusted the comparisons to match. If this is undesirable or noisy, I'm happy to revert and just keep appending fields.
=> netaddr: add IP.IsGlobalUnicast

netaddr.go
This adds IsValid to IP, and corrects the spelling of IPPrefix.Valid,
IPPort.Valid, and IPRange.Valid to be IsValid, keeping deprecated
Valid wrappers for now while code is fixed.
Fixes #194
=> Add IsValid method to IP, fix Valid method naming on the other types.

netaddr_test.go
=> netaddr: add invalid from/to test cases for ParseIPRange

example_test.go, netaddr.go, netaddr_test.go
This is probably the last method I need for a bit. Notably this mirrors the upcoming https://tip.golang.org/pkg/net/#IP.IsPrivate for Go 1.17.
=> netaddr: add IP.IsPrivate

fuzz.go, netaddr_test.go
The appendMarshaller type is declared in both fuzz.go and netaddr_test.go,
which causes the fuzz tests to fail to build. Use the one in netaddr_test.go.
While we're at it, rename it to appendMarshaler.
=> netaddr: fix fuzz build

netaddr_test.go
=> netaddr: add test for IP.UnmarshalBinary with bad byte length

example_test.go, ipset.go, netaddr.go, netaddr_test.go, stackerr_test.go
Please review commit-by-commit, but note that some later commits refine the earlier ones. (I can squash if desired, but I thought the evolution might be useful and easier to review than a mass rewrite.)
The overarching goal is to make the error messages from IPSetBuilder more useful and actionable.
I'm not particular about any of the details. I tried to make the error messages single-line, because that is my preference (for logging, etc.), but a more verbose multi-line form might be more useful.
=> improve IPSetBuilder error messages

netaddr.go
Fixes #211
Signed-off-by: Josh Bleecher Snyder <josh@tailscale.com>
=> remove "netaddr: " prefix from errors

.github/workflows/linux.yml, fuzz.go, stackerr_test.go, tools/tools.go
* `gofmt` with Go 1.17 to add `//go:build` tags
* Add Go 1.17 to test matrix
* Check formatting in CI
=> Update CI to Go 1.17, check `gofmt` in CI
