netaddr.go, netaddr_test.go
This is all I need at the moment. The test can be expanded with more conditions later, or broken into smaller tests. Either way is fine by me.
Fixes #5.
=> netaddr: add IP.IsMulticast method

netaddr_test.go
Easy test coverage, and verifies that things will work sanely with JSON/text encoding.
=> netaddr: test coverage for IP text marshaling

netaddr_test.go
Came here from https://github.com/golang/go/issues/37921 :) 
Just a small PR adding some more test coverage here.
=> More 4to6 test cases

.github/workflows/linux.yml
Mostly copied from tailscale repo. I think this will work, but this is my first time setting up Actions.
Fixes #13.
=> ci: set up GitHub actions workflows

.github/workflows/staticcheck.yml
The repo has no issues as of https://github.com/inetaf/netaddr/commit/b2a8e96b315606fbfa64407fde40c55913ac5aac. This will enforce that for future commits.
=> ci: add staticcheck workflow

netaddr.go, netaddr_test.go
This is my first shot and feedback is welcome. I left TODOs for things I'd like feedback on.
For allocations, at the moment we have:
```
./netaddr.go:289:13: make([]byte, len(b)) escapes to heap
./netaddr.go:310:12: v4 escapes to heap                                                  
./netaddr.go:314:12: v6 escapes to heap                                                  
./netaddr.go:320:12: v6 escapes to heap 
```
Fixes #9 .
=> netaddr: implement IP.Prefix to produce IPPrefix

netaddr_test.go
Add tests for previously uncovered functions IP.Is4, IP.Is6 and IPPrefix.IPNet.
=> Add additional tests

netaddr.go, netaddr_test.go
Mirrors the existing From* APIs.
=> netaddr: add FromStdIPNet to convert *net.IPNet to IPPrefix

netaddr.go, netaddr_test.go
=> netaddr: add IPPrefix.{M,Un}arshalText methods

netaddr.go, netaddr_test.go
=> Add IPv6Raw, IPFrom16, IP.As16, FromStdIPRaw, modify FromStdIP

netaddr.go, netaddr_test.go
Using gofmt from Go 1.14.4
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> all: gofmt

netaddr.go, netaddr_test.go
Not done, but you can see where I'm going. Just need to map ranges to a covering of `[]IPPrefix` now.
/cc @josharian @danderson @mdlayher @crawshaw
=> Add IPRange, IPRangeSet & friends to work on sets of prefixes/ranges

netaddr.go, netaddr_test.go
=> Add IPRangeSet.ContainsFunc

netaddr.go, netaddr_test.go
=> Don't allocate parsing IPv4 addresses

netaddr.go, netaddr_test.go
I just encountered the second place where this was implemented in Tailscale, each different ways.
=> add IPPrefix.IsSingleIP

netaddr.go, netaddr_test.go
=> implement TextMarshal and TextUnmarshal for IPPort.

netaddr.go, netaddr_test.go
=> add IPRange.Overlaps

netaddr.go
=> netaddr: fix typo in IPSet.Ranges

netaddr.go
This lets us provide slightly better parse error information (including
the position at which the error occurred), and also speeds up successful
parsing in some cases, because error formatting is delayed beyond the
execution of ParseIP.
```
name                   old time/op    new time/op    delta
ParseIP/v4-8             24.9ns ± 1%    24.0ns ± 2%  -3.58%  (p=0.000 n=8+10)
ParseIP/v6-8             90.0ns ± 4%    92.7ns ± 4%  +3.03%  (p=0.006 n=10+10)
ParseIP/v6_ellipsis-8    69.1ns ±10%    62.4ns ± 5%  -9.60%  (p=0.000 n=9+9)
ParseIP/v6_v4-8          73.4ns ± 4%    66.9ns ± 3%  -8.81%  (p=0.000 n=9+9)
ParseIP/v6_zone-8         221ns ± 2%     215ns ± 2%  -2.58%  (p=0.000 n=10+10)
```
=> introduce parseIPError as an explicit type.

netaddr_test.go
=> Lock in more constructors and methods that must be allocation-free.

inlining_test.go, netaddr.go, netaddr_test.go, uint128.go
A bit of fun for me to wrap up 2020. I'm not wedded to these, so if you think it's too much, we can revert.
=> fun with bit twiddling

inlining_test.go, uint128.go, uint128_test.go
This is the last of these PRs for a while, I think/hope. :)
=> make bitsSetFrom and bitsClearedFrom loop-free

go.mod, go.sum
See https://github.com/go4org/intern/commit/3eb7198706b254cddea46d066da7316b2620ba7a.
=> go.mod: bump go4.org/intern to pick up finalizer ordering change

ipset.go, ipset_test.go
=> Add ipset.Overlaps.

example_test.go, inlining_test.go, ipset.go, ipset_test.go
=> ipset: split into a mutable builder and an immutable set.

netaddr.go, netaddr_test.go
Creates an IPPrefix from an IP and a netmask byte slice.
Fixes #133
Signed-off-by: Terin Stock <terinjokes@gmail.com>
=> netaddr: create IPPrefix from netmask

README.md
Fix the link to point to the actions of this project 🙂
=> README: update github actions link

.gitmodules
=> Use HTTPS instead of ssh for submodule

fuzz.go, netaddr.go, netaddr_test.go
Signed-off-by: Maisem Ali <maisem@tailscale.com>
=> netaddr: have IP implement BinaryMarshaler/BinaryUnmarshaler.

inlining_test.go, netaddr.go, netaddr_test.go
See the second commit for benchmark numbers and discussion.
=> optimize IPPrefix.MarshalText

example_test.go, netaddr.go, netaddr_test.go
I need this too, so I whipped it up. PTAL.
Fixes #195 .
=> netaddr: add IP.IsUnspecified

fuzz.go, ipset.go, ipset_test.go, netaddr.go, netaddr_test.go
The Valid method is deprecated, use IsValid instead.
=> netaddr: use IsValid instead of Valid

fuzz.go
Fixes #208
Updates #204
Signed-off-by: Josh Bleecher Snyder <josh@tailscale.com>
=> fix fuzz build
